from src.database.dbcontroller import DBController

# Crear una instancia de la clase DBController
bd = DBController()

# Conectar a la base de datos
bd.connect()
      
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('agradecimientos', 0,%s,2)", ("Gracias",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('agradecimientos', 0,%s,2)", ("Muchas gracias",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('agradecimientos', 0,%s,2)", ("Gracias por tu ayuda",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('agradecimientos', 1,%s,2)", ("De nada",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('agradecimientos', 1,%s,2)", ("No hay de que",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('agradecimientos', 1,%s,2)", ("Estoy para ayudarte",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 0,%s,2)", ("camarero",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 0,%s,2)", ("puede venir un camarero?",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 0,%s,2)", ("necesito un camarero",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 0,%s,2)", ("camarero por favor",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 0,%s,2)", ("solicitar camarero",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 0,%s,2)", ("necesito ayuda",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 0,%s,2)", ("mesero",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 0,%s,2)", ("mesera",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 0,%s,2)", ("puede venir un mesero?",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 0,%s,2)", ("necesito que me atiendan presencialmente",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 0,%s,2)", ("atencion real",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 1,%s,2)", ("Un camarero vendra enseguida",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 1,%s,2)", ("Claro, en un momento llega el camarero",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('camarero', 1,%s,2)", ("El camarero ha sido avisado",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pagar', 0,%s,2)", ("Cuanto es?",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pagar', 0,%s,2)", ("Cuanto tengo que pagar?",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pagar', 0,%s,2)", ("Quiero pagar",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pagar', 0,%s,2)", ("Quiero la cuenta",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pagar', 0,%s,2)", ("La cuenta por favor",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pagar', 0,%s,2)", ("Puedo pagar?",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pagar', 0,%s,2)", ("Pagar",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pagar', 0,%s,2)", ("La multa por favor",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pagar', 1,%s,2)", ("Claro, enseguida le traigo la cuenta",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pagar', 1,%s,2)", ("Un momento, le traigo la cuenta",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Quiero",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Me gustaria",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Deseo",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Necesito",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Quiero pedir",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Me gustaria pedir",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Ponme",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Dame",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Traeme",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Quiero ordenar",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Quiero hacer un pedido",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Quiero hacer un encargo",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 0,%s,2)", ("Anota",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 1,%s,2)", ("Pedido anotado",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 1,%s,2)", ("Pedido recibido",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('pedir', 1,%s,2)", ("Recibido en cocina",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('despedida', 0,%s,2)", ("Adios",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('despedida', 0,%s,2)", ("Hasta luego",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('despedida', 0,%s,2)", ("Hasta pronto",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('despedida', 0,%s,2)", ("Nos vemos",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('despedida', 0,%s,2)", ("Chao",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('despedida', 0,%s,2)", ("Bye",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('despedida', 1,%s,2)", ("Adios, que tengas un buen dia",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('despedida', 1,%s,2)", ("Hasta luego, cuidate",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('despedida', 1,%s,2)", ("Nos vemos, gracias por tu visita",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('saludos', 0,%s,2)", ("Hi",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('saludos', 0,%s,2)", ("Hey",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('saludos', 0,%s,2)", ("Hola",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('saludos', 0,%s,2)", ("Hola que tal",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('saludos', 0,%s,2)", ("Buenos dias",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('saludos', 0,%s,2)", ("Buenas tardes",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('saludos', 0,%s,2)", ("Buenas noches",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('saludos', 0,%s,2)", ("Saludos",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('saludos', 1,%s,2)", ("Hey :-)",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('saludos', 1,%s,2)", ("Hola, en que te puedo ayudar",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('saludos', 1,%s,2)", ("Bienvenido, ¿en que puedo ayudarte?",))
bd.execute_query("INSERT INTO intents (tag, Tipo, Texto, indice_apoyo) VALUES ('saludos', 1,%s,2)", ("Estoy encantado de poder ayudarte",))

# Ejecutar una consulta
# Desconectar de la base de datos
bd.disconnect()
